# Generated by Django 4.0.6 on 2022-07-13 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0002_todoitem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='username',
        ),
        migrations.AddField(
            model_name='todolist',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
