# Generated by Django 4.0.6 on 2022-07-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todoitem_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListShared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_sharer', models.IntegerField()),
                ('username_consumer', models.IntegerField()),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.todolist')),
            ],
        ),
    ]
